### ISSUE TITLE
Implement not-implemented parts of code

### ISSUE THREAD

**Issue by ZryletTC** [pcdshub/archapp#6]
There are still some lingering NotImplementedErrors

**Comment by ZLLentz** [comment]
@silkenelson reported this again in a trello ticket yesterday. The most egregious of these errors is that the default arguments `xarray=False` for a simple `.get` will never work because of:
https://github.com/pcdshub/archapp/blob/736ddc9cf4bc87d1fb1bb4824ac45789319f254a/archapp/interactive.py#L108-L110
